version: '3'

services:
  realtime_mt5:
    build:
      context: ../realtime_metatrader/
      dockerfile: Dockerfile
    container_name: realtime_metatrader
    volumes:
      - ../realtime_metatrader/config:/config
    ports:
      - 3001:3000
    env_file:
      - .env
    command: sleep infinity

  realtime_data:
    build:
      context: ../realtime_data
      dockerfile: Dockerfile
    container_name: realtime_data
    volumes:
      - vscode-dev-1:/root/.vscode-server
      - reatime_data_cache:/root/.cache
      - reatime_data_ipython:/root/.ipython
      - /root/workspace/realtime_data:/root/app
    command: sleep infinity
    secrets:
      - user_ssh_key

secrets:
  user_ssh_key:
    file: ~/.ssh/id_rsa

volumes:
  vscode-dev-1:
    external: true 
  reatime_data_cache:
    external: true 
  reatime_data_ipython:
    external: true 
  


